/*
    Copyright 2021, 2022, 2023 David Healey
    
    This file is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    
    This file is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.
    
    You should have received a copy of the GNU General Public License
    along with This file. If not, see <http://www.gnu.org/licenses/>.
*/

namespace Paths
{
	reg pathData;
	const icons = {};

	// X - Reza
	pathData = "277.t0lP.73PWjOVCwFhFC4PLxVUCI1UND4PvzMUCckCQNTuzO0PHZLjCEVYSMjXZ6GjCUf0RMTnJ.4PEXsTCIuvONTXkM0PrwJ+MND6wa0PrYlMLNTXkM0Phco6KNTAVK0Pdo2hCUf0RMDzxr3PgU1TCIV.qq3P+S+TCEv5JNTbcS0PPKyhCwHaUMDaVjOiCcQ9XMDaPKyhCIZgbMjXArthC4OEcMT.qq3Pw0eWCAsLKNTyL50Ph4mdKNTJb70P259hCkBGeMjY1v3PMynWCwFq723PBAvVCwl7B+3PMynWCIVvJ.4PovwWCouePNTJb70PHZLjC0LidMjXW4PjC8R+cMzUND4P8RQWCgnwPNjnEx0PiUF...";
	  
	icons.x = Content.createPath();
	icons.x.loadFromData(pathData);

	// Backspace - Material (1:0.77)
	pathData = "175.t0VyLhAQiiiyCwF..d.Q..fmCwVyLhAQ333VCwF..VDQ333VCwF..VDQiiiyCwVyLhAQiiiyCMVau6FIDgii4NDaNNVKDoOomNDatfkMDgii4NDappxND4S5uNDaKXiLDA..dNDappxNDErELNDatfkMDcbbBNDaNNVKDYvVTNDau6FIDcbbBNDaxw4GDErELNDaQDIJDA..dNDaxw4GD4S5uNDau6FIDgii4NzXkA";
	  
	icons.backspace = Content.createPath();
	icons.backspace.loadFromData(pathData);

	// Email - Material (1:0.8)
	pathData = "248.t01Ly1.QYl4yCE2djr.QYl4yC4iTIPjG0u7PwA.fGPDoPg7P..3ADMyLCODa..3ADkYlwMTb..3ADcqWmMjORk.QBWAXCE2djr.QLyLVCMyrMPDyLi0Pr0LS+PDyLi0PwY31AQDyLi0PC25PDIbEfMTb..XQDcqWmMD..VDQYlYbCwF..VDQyLyvCEG..VDQjBExCMbqCQjG0u7PwY31AQTlY97PMyzODkYlOODayLaCDkYlOOzXsA.flPzLyP5Pr0LS+PzLyT3Pr0LS+PTlYF2PrA.flPDyLe4PrMyrMPTlYF2PrMyrMPzLyT3PrA.flPzLyP5PiUF";
	
	icons.email = Content.createPath();
	icons.email.loadFromData(pathData);
	
	// Lock - Material (0.76:1)
	pathData = "530.t0F..8.Q..16CEmlMv.Q..16C0rwIPjYRq9PwA.fGPTyDY9P..3ADA.3eODa..3ADA.XRNTb..3ADQy9KNTyFm.QZ11gCEmlMv.Q..tfCA.POPD.fK3PrA.HSPD.fK3PrA.HSPD..a1PwA.HSPDZVZzPMqLFDQy5uLTbZVmGDA.PYLD..ZBQ..TFCEmYJ5BQ..TFCMSMzPDMq+xPwA.34PDZVZzP..dNDA.vlMDa..dNDA.3BNDa..bODA.3BNTblIOPDA.3BNzL4LDQZ11gCEG..VDQzr+hCA.fEQD.fI4PrA.fEQD.f+8PwA.fEQTyDY9PyjyPDYlzpOTblIOPDA.XuOD..2CQ..16CwF..8.Q..16CMVa..nIDA.nHOTblIaJDA.nHOzL4uBQlIAwCEG..4BQMS3uCA.PtPD.fj6PwA.PtPDM6J6Pyj+JDoYKtNTblIaJDA.noND..ZBQ..ZpCEmlMMBQ..ZpC0rAgPjls35PwA.vdPDM6J6P..rGDA.H4NTb..rGD0Lg+NTyFDBQlIAwCEmlMMBQ..JxCA.flPD.fh7Pi0F.fqAQ..tfCwF.fHCQ..tfCwF.fHCQ..rYCEG.fHCQ..1TCA.utPD.PWzPwA.VqPD..gyP..nIDA.P3LTb.fZHDA.P3LD.D4AQ..cQCEG.fqAQ..1TCA.3ZPD..a1PrA.3ZPD.fK3PiUF";
	
	icons.lock = Content.createPath();
	icons.lock.loadFromData(pathData);
	
	// Encrypted (1:0.8)
	pathData = "289.t0F.vBBQ..TsCwF.PwBQ..TsCwllUnBQZFDmCEmlEvBQZFklC0rHsPDMiZ4PwA.PtPTyzK4P..jKDA.fNNTb..jKDQyFHNzL4uBQZ13fCEmYxlBQ..feCA.flPD..32PwoYSiPD..32PMaPHDoYiCNTb..rGDQyFHND..6AQ..niCEG..6AQMSujCMS2ePDMiZ4PwYl9fPjlQo4PlotHDoYPbNDa..KHDA.P0NzXsA.flPD..t9Pw0LBYPD.3R9PlQDDD0LlLOTb..3ADoYdzND..d.QlYvkCwF..d.Q..3SCwF..ZBQ..PHCwF..VDQ..3SCwF..VDQlYvkCEG..VDQZlGsCo4t7PTyXx7PwMy8yPD.3R9P..nIDA.fqOzXkA";

	icons.encrypted = Content.createPath();
	icons.encrypted.loadFromData(pathData);
	
	// Library - Reza
	pathData = "1059.t0lqGcfPfpgCBIVkCqfPfpgCBQgqOHDBr1fPov8DBwIQHHjXwf.EB8QAHHDY6PgPqw6ABMGZTHD88cfPhYNzUHDRgYfP1ixEB0K8DHj67ggPoEw.BIVrxQhPlX.4AATswHDz22aPf+DOBMEteFjXhqOPBUIFRFTwfjiPeo6jAULH4HzW5NYPhULH4HzW5NYPP0fHBUKxUGDTMRgPudD+AIVgqEgP9S8.BMGZLHzbnSfPJbsABMG5DHDacnkcAMG5DHjX..faAMb8BHTsHiVP88C.BUKxnEj03oePhUKxnEjx1QePnueaAsDCuGD0MYWP2ix5AwF6QcfP2ix5AI1zMqfP2ix5AIEtOHDuIodPmY9DBItdeGjXdSxGBAnZ+FjnE+hPDB7iAwGE5HzT3RVPhcjs7HzsyWUPRKZNBsYlQET..XiPalYTAw114KcPalYTAIFpFibPalYTAoZ7DGDZloUPdoavAsZ7hEjX1N+pAwxgPFTOJ7WPRKBzAY7ReEDjBadPh046UEDmDudP5QATAsFuxGjdT.UPVim9AIldT.UP88i.B046YEjiWZfPpbHZAcP.IHDaPKxWA014KHjXmZbUAMGZNHTmu+TPaQdDB046OEDjBWgPh046OED7mpgPFuTVAIY6dHz8ScVP77UHBwFzh7UPsc9HBI1oFWUPyglIB046OEzVjmhPc99SAAovsHjXc99SAIDX0HDx1YVPJw3NBAsHAFjRLtiPr0NeBFjRLtiPrYPfBFzXPtiPhYPfBFzXPtiP5lD2AMFj6Hz0iZfPiA4NBI1v04fPiA4NBoDiSHzaRpiPpFGFBgnkyHjXscFIBIChhHD+oFiPGD3CBwIQ7HzShAfPhQJ7.IzzhLePAVQNBopwzGTfUjiPpZL8AIVfUjiPpZL8AIw.hHjdosgPRLHEB0eptHjXGEVDBQxVzHzKcwfPR1VMBwLyFHjjsUiPr8SM1EjjsUiPhIx1sED56MiPWOJZAwIwvHz0ihVPPJbKBI10ihVPJFrJBov0sEjRLfhP1ihcAoYFlHDatdzABoYFlHjXsHqBBoYFlHT358fPveZIBAplSHjRLBhPhsaRUHDRg8gPHEtEBA9ycHjpwggPAV4FBIVamQhPqbnBBwepwHD..7dPbRDOBAovPGjXjBOPBULHCGTfUjiPbRLwAEXE4HDmDSbPhEXE4HDmDSbPRLfHBMGZCHjDCRgP1ipEBI1QgEgPcnEGB8RWLHDir0gPLyrABwHacHDa+TicAwHacHjXhrcaAItdaHz0ihVPVNLFBc8nnEjhAWgPhc8nnEDg.KgPJbcaAQzBPHj8nXWPThgCBwlqGcfPThgCBMVaX5V0A8nvAFDatdjHB8nvAFDaPfMFB88SbFDab8nvA88SbFDaX5V0A8nvAFzXkA..";
	  
	icons.library = Content.createPath();
	icons.library.loadFromData(pathData);
  
	// Sync - Material
	pathData = "878.t0FIBaBQFUcVCEmuGwBQFUcVCI9ovPjlYH1PwY.B0Pj0co1P9NFNDoYV4MDafFgNDohLANDa..hLDohLANTbJxKLDohLANT7P+BQdkvfCE2Uk6BQQBNgCcU4tPDemd3PwcU4tPjYto3PwC8KDoYQLNTbJxKLD0LGNND.fHCQMygiCwFVEIDQMygiCEGynNDQMygiCYFkDQjlEw3PwA.fEQjYto3P..XQDw2oGNDa..XQDoYtNMTb..XQDQ7JIMjYTRDQd0WQCEGynNDQ36bPCgUQBQD9NGzPwId3.QD9NGzPHY+OD4UeEMTbtpvODQ7JIMjqJ7CQZlqSCwlqJ7CQxlYbCwlhP2CQRh5ZCEWEIjCQRhFUCcUPyPDOznzPwoYdsPD...zPjHrIDA...MTbwaZGDA...MzLsXAQNyuTCEWcy5.QZleYCMyxJPDgvK3PwYlMJPDtCU3PwKrBD8piGNTb08zBDoY1INjlIx.QDBqhCEWc61.QDh5hCoY8NPDOnp3Pwg6KPPD.nl3POTMDD0LUGNTb39.EDQyn1MjGrmAQ7vCZCE2hH+AQFUcVCQhvlPjQUm0Pi0F28XBQdUwyCEmPvFBQdUwyCQnGcPDMyq7Pw0LiXPjEQa7Pp6NEDEUk+NDaf4tDDkPL6NDa..tFDkPL6NTb0MDGDkPL6NzCuzAQVmUtCEGpZ3AQvJ3sCgpFdPDt6R6PwgpFdPTyzG6PO7RGDoYGvNTb0MDGDYlQtND.fqAQlYjqCwFp5p.QlYjqCE2LWk.QlYjqCo4ZHPjlc.6PwA.fGPTyzG6P..3ADg6tzNDa..3ADYlAUOTb..3ADEUyWOjlqg.QDRZ1CE2LWk.Q3t21CgptJPDt6s8Pw4gGLPDt6s8P3lPCDQHoYOTbQUeCDEUyWOTT02.QlYP0CwVT02.QQU2vCwFgP8.QV2lwCEWcCRAQ.fUzCEOfZPD.rZ8PwYlefPD..v8Pb2iIDA..bOTbJhzKDA..bOjuwZCQyLqzCEW7Z3CQlYVxCIDIBQTyzl6PwoYxBQjlgc6PXUjPDYQ4zNTbODbPDEIZxNjY1ADQQBWrCEmhD8CQQhGrCYlB9PDy3E6PwgDz7PTE4I6PwqBODgDyzNTbLCPNDAI7.ODIbLCQ2K.xCEWc2zBQcUwyCwcOlPTWU77PiUF";
	
	icons.sync = Content.createPath();
	icons.sync.loadFromData(pathData);

	// Logout - Material
	pathData = "572.t0FVY0.Q2sR2CEm55q.Q2sR2CUWOIPTivl8PwA.fGPDo0X8P..3ADgLdQODa..3ADAmCUMTb..3ADgKkKMTc8j.Qj6IQCEm55q.QRjZOCgUVMPjDo1yPrQgFjPjDo1yPwYDVkPjDo1yPD9hIDQQBAMTb.avIDYQZDMDvFbBQFYVRCEGvFbBQ1MlSCQ3KlPD83F0PwYDVkPjbNT0PTnAIDImCUMDaXkUCDImCUMDaXkUCDgLdQODaTnAIDgLdQOTbFgUIDgLdQODguXBQIixzCEGvFbBQJiM0CArAmPTXWc8PwArAmPT9Um8PD9hIDgKfaOTbFgUIDg2JcODEZPBQ3sR2CwFVY0.Q3sR2CMVaJf2NDgU1iNDaor2GDgU1iNTb7yiGDgU1iNjtk0AQXkhnCEWeNxAQVkGnC0mibPju524Pw0mibPzI7s4P5VVGDgVzYNTb7yiGDgpIXNTJ68AQnZBlCwVFZsCQnZBlCw1tqQCQrmjhCE2lRNCQrdIhCYglyPju.Y3PwYYnyPDzoO3PvpGMDwIJBNTbPOUMDY1Y.NjPNZCQl+EfCEGsHeCQlgEfC4Tp3PjlYH3PrY1mDQDxEn4PwA.fEQj+Fu4P..XQDYeGdNTb..XQDQNcfNjYeRDQYXinCwFQ3hCQPQftCEGqZeCQFV7tCQep1PDDut6PwITd0PjlXt6PJKIMDU104NTbG96LDAiE3NzQCOCQLiZsCEm.GOCQnsyrCEBnzPTJIF6Pro.d6PDVYO5PiUF";

	icons.logout = Content.createPath();
	icons.logout.loadFromData(pathData);
	
	// Login - Material
	pathData = "225.t0lYlMBQ..feCwFWO7AQT35gCwFtdbBQMy7kCwF..d.QMy7kCwF..d.QzLCoCwFtdbBQzLCoCwFWO7AQrGEsCwlYlMBQ..PuCwlYlKCQ..fmCwlYlMBQ..feCMVaMyzODYlYIODa..nIDYlYIODa..nID0LyUODaMyzOD0LyUOjXBWqPD0LyUOD..VDQRgCzCA.fEQjYlk7PrA.fEQDMyT1PhA.fEQTWOd0PBWqPDclYLMTyL8CQmYFSCwF..ZBQmYFSCwF..ZBQzLSYCwVyL8CQzLSYCwVyL8CQlYVxCMVY";
	
	icons.login = Content.createPath();
	icons.login.loadFromData(pathData);

	// User - Material (1:1)
	pathData = "321.t0F..ZBQ..fmCE2La.BQ..fmCoYiaPTyjS4PwA..WPjlIu3P..vEDA..9MTb..vED4LajMjlMtAQlYiTCE2La.BQ...PCA.flPD...zPw0L4rPD...zPlIWLDYlMRMTb..fMD4LajMD..XCQ..feCEG..XCQZl7hCYlbwPTyjS4Pw0L4rPD..34P..nIDA..dNzXsA.fGPD..v8PrA.fGPTyLY7PwA.fGPjY196P.HSBD0LL5NTb.PtBDQypzNzLy1.QzLbrCEWyzNAQZF7pCA.5YPTy.i5PwMyFfPD..W5P..nIDA.vkNTbMSNKDA.vkND.XLCQMCLpCE2LKkCQZF7pCwLS+PDMCG6PwA.GBQDMqR6P.37PD0LL5NTb..XQDYls+ND..VDQMyjwCwF..VDQ...2CwF..d.Q...2CMVY";

	icons.user = Content.createPath();
	icons.user.loadFromData(pathData);

	// Eye - Material (1:0.68)
	pathData = "440.t0F..ZBQWz0sCEmtHuBQWz0sCM5duPjQ2+5PwwnKyPDcQh5PL5xLDA..dNTbL5xLDwnaSNzn68BQ5h.iCEmtHuBQnKJgCA.flPD5hR3PwYzMgPD5hR3PdQXGDoKBLNTb0EcFDwnaSNTcQmAQ..fmCEWcQmAQzEIpC4EgcPjQ2+5PwYzMgPzEcc6P..nIDcQW2NzXsA.flPz12z5Pw4EUiPz12z5P3vQHDA4wnNTbSPtGDYzUjNzDj6AQ..fmCE2Dj6AQ5h5kCgCGgPDb3L4Pw4EUiPTIH63P..nIDUBxNNTbitZJDUBxNNDxiuBQvgyjCEm6a3BQ5h5kC49FtPD..34Pw49FtPjQWQ5PHO9JDA4wnNTbitZJDs8MsND..ZBQaeSqCMVa..nIDEcQHOTbwZCGDEcQHODUBOAQjmLuCE28Ms.Q12TrCA.fGPD..34PwceSKPTBxp3PTI7DDgCa9MTbwZCGD0EcmMD..ZBQcQ2YCEGTICCQcQ2YCwZO4PDNr42PwofrAQTBxp3P..XQDA..dNTbJHaPDYeSwNDq8jCQjmLuCEGTICCQQWDxCA.flPTzEg7PiUF";
  
	icons.eye = Content.createPath();
	icons.eye.loadFromData(pathData);
  
  	// Offline - Material (1:0.83)
  	pathData = "610.t0VUEpCQlYRzCwVy7HBQyLEnCEGuy7AQu6anCIhkbPjYVR5PwgH9YPj2sc5P2c9EDEQrqNDaqpmDDUUkfNTb7tHEDMybbNzcuaAQZlUlCE2LSkAQ..jkCoYBbPTyrO4ProYNVPTyLg3Pww6jSPzLCr3PMiTDDYlSNNTbd2uCDoYlQNTyry.Q7takCwF..d.Q..phCEWDQl.Qd2mgCc2xKPjpxL3Pw4cANPz6N+2PqpHDD4c24MDad2wBDspJjMDa7tqCDMyrUMDaDQjODsp5IODaUUnNDYlIQOzXsA.flPjHhi7PwoYxiPjHhi7PhndHDspDEOTbqp.HDMyPAOzpJ.BQ2c+tCE2pJ.BQppnsCIh5gPDuKK6PwoYxiPTyL75P..nID0LCuNTblYSJD0LCuNj2UrBQ7trrCEWU0yBQppnsCUU8rPzc2u6PwUU8rPzLCE7PdWwJDspDEOTblYSJDIh3HOD..ZBQhHNxCMVad2aMDQDIpNDal48LDUUYlNDau6eLDYlohNDahHKJD0LCPNTbU0dKDYUEQNz65ICQHhUkCEGhHbCQ7tYlCUUg5PTUUB5Pr4cu0PDQjn5Pi01LS.DQ7takCEmHZrCQZl7hCA.izPzLqX3Pw4c+sPTyLB3P..nID0Li.NTbMSRID0Li.NjYhOBQl4KfCEG.fJBQ..OfCUUUgPzLSE3Pr8tuZPTyLg1PwYlkcPzLyT1PqZHHDcloiMTbua2HDoYFhMD..ZBQZlgXCEGuq9BQZlgXCUUm2PzpJ+1Pw8ti+PDu602P..XQDA.nJNDayLAPDw6tUNzXkA";
  	
  	icons.offline = Content.createPath();
  	icons.offline.loadFromData(pathData);
  
  	// Heart - Material (33x29)
  	pathData = "662.t0F..ZBQ4cR0CEG5UVBQ4cR0CI2njPj+9Q8PwsOriPzfVO8PKjuHDw8XRODaDcmGDsOFJOTblHUEDI8L4NzDo4.QLgWpCEG..d.QHyalCA.fGPDCDf3PwA.fGPDuuN2PYCDCDQFrfMTb2FPDD4PrMMzgHfAQNDaSCEmlIvAQNDaSCMb0ePDbTT0PwwdniPz42w0P..nIDUkDrMTb5.ZJDc9cbMTsD0BQvQQUCEGLoCCQNDaSCk28zPjCw1zPwoj+6PjCw1zPn7KPDQFrfMTb..XQDw6qyMD..VDQLP.hCEG..VDQHyalC4il9PT69k5PwsGs2PjDAk6PgHnKDIiIJODanMfJDImZROTbI1TJDUZ1SOzycgBQJBH0CEWEtcBQ4cR0CA.flPTdmT8Pi0VyrPBQ7zOfCEG5GHBQl04bC454dPjj7q1Pwk2waPzpaI1PGh.FDs5VhMTbDKwDDs5VhMDtd+.QbYzaCEGppx.QMDCeCgppLPTYOf3PwgppLPDHxB4PhF5CDA7RZNTbXhoDD4U4iNj+3ZAQ4uNqCEGXYqAQTJesCYOPePzx+16PwcHpiPj.MV7P..nIDoNwJOTb5cUJDk2oEOjB+1BQBzbuCEGnlHCQUJesCEWQ1PDqZy5PwYDY5PDwBO5PMyUOD4AJZNTbYUEPDAXiPNTVUADQLP.hCEWVUADQMDCeCwpF8PDWF81PwA.34PzpaI1P4cOMDs5VhMTbPsRLDs5VhMzsQ3BQQHtZCEGF3qBQKh1bCwKtnPDO8C3PwIERnPjFUI3PVa6IDI87BNTbTUxIDonjCNDwxYBQJJ4fCEWM.WBQJJ4fC0AJkPjzyK3PwA.jjPjFUI3PMyBIDwS+.NzXsA.flPDY424PiUF";
  	
  	icons.heart = Content.createPath();
  	icons.heart.loadFromData(pathData);
  	
  	// Heart Filled - Material
  	pathData = "205.t0FKcpBQVrrzCIlDJgBQpNv0C4dsjPjpCb8PSKlHDw1tRODawxfHDEsGROjXJ2eDDo.D0ND..d.QZlfnCsb4GPzRMo3PhYLEHPT+M+2PC3qBDMJ2qMTEN7.QN2AXCI1QgbAQ+egRCQeFgPT9dQ0PVvmIDIxjsMjX238JDkuWTMD4VWCQrheRCYg58Pjyc.1PhghNBQznbu1PkMNQD0ey+MDXRTDQK0jhCIF..VDQZlfnCIl95PjBPT6P5stJDQhORODarzoJDYwxROzXkA";
  	
  	icons.heartFilled = Content.createPath();
	icons.heartFilled.loadFromData(pathData);
  
	// Key - Material (23x12 : 0.5)
	pathData = "566.t0lgrdAQYgLpCEGMyUAQYgLpCYb2SPzecV5PwkERRPToxI5PYgjDDA..dNTbYgjDDwUiYNjwcOAQAJlkCEGMyUAQmdyjCYHqWPzo2L4Pwgc4YPzo2L4PEs2FDEnXVNTbxBQGDwUiYNjrPzAQ..fmCEmrPzAQkJmnCUzdaPzecV5Pwgc4YPTVHi5PFx5EDkExnNzXsYHqWPzBY46Pw4z6PPzBY46PmdCCD0a5zNTb..3AD8ldqND..d.Q..fmCEG..d.QQVHjCc5MLPzPVb3Pw4z6PPj5Ms2PFx5EDodS6MTbqACGDodS6Mjpb+AQZlgfCEG5HNBQ9vngCoOrkPjdS23Pr4aZ8PjdS23PrA.fEQD..34PrwoW4PDxBY6PrAm9yPjgr35PrMjktPDxBY6PrQ81nPjgr35ProOrkPjgr35PwgNhiPjvyU6Ppx8GDYl44NTbqACGDsPV9NjgrdAQKjkuCMVaFx5EDIKjyNTbkJ2FDIKjyNT2O4AQLtuqCEGEsDBQlYlpCwoGhPDKjM5PrIxhpPDKjM5PrI7btPj1pi5PrAm9yPjExB5Prc0v3PD0af5PrETz8PD..34PrsxG6PD0ah4PrwoGhPD0ah4PwQQKgPjlYF4Pc+jGDQGAMNTbkJ2FD4zaHNjgrdAQN8FhCEW34LAQN8FhCcvCPPj.E63Pw0B4LPjsZT4PsPNCDA..dNTbsPNCDoT4lNzAO.AQ9qSqCEW34LAQxB4rCYHqWPjrPN6PiUF";
  
	icons.key = Content.createPath();
	icons.key.loadFromData(pathData);
	
	// Deploy - Material (0.9:1)
	pathData = "418.t0VNNLBQmYRzCwVNNLBQLXenCwlii4.QvVfhCwlii4.QLXStCwVNNLBQmYRzCMVaGGeJDclIQODaxwoODwfM4NDaxwoODAaAJNDaGGeJDwf8gNDaGGeJDclIQOzXsA.flPj5SX4PrgH55PDd2y2PrA.flPDGG2zPrc2ERPDd2y2PrA.flPj5SX4Pi01wwq.QDQTwCE26Nk.QJ80vCc2YHPDrEA7PwA.fGPzErz6P..3ADIhX4NDa..3AD4cmBNTb..3ADM8o8Mzcmg.QfR2cCE26Nk.QrETbCcb7JPDd201PrkiCiPD1BXyPwEQrjPD43HyP..nIDQNNxLTbu6DJDQNNxLzwwmBQXKfMCwVNNHDQ3cWaCEWDwNDQrETbCgHlDQDnzc2PwA.fEQzzm12P..XQD4cmBNDa..XQDIhX4NTb..XQDcAK8NDhXRDQvVDvCEWDwNDQJ80vCkiCBQDQDU7Prcb7oPDk9C9Pw8tSnPjiiK9P..nID433hOTbQDKID433hOTNNLBQT5O3Cw1wwq.QDQTwCMVa..nIDA..dNzXkA";
	  
	icons.deploy = Content.createPath();
	icons.deploy.loadFromData(pathData);
	
	// Caret down - Reza
	pathData = "293.t0FxW.lPvlHUBw1+0zkPvlHUBwFAMfkPcevVBIVeYekP3izVBYijWIjwsskPCjzUBYbaaIjXLAvUBYbaaITA4ZkP4izVB0WgVIT2GrkPrMHWQIDrIRkProqdNIDrIRkPhUnBNIDrIRkPdWZSBwo2TIj.60jPUCVUBIVIP0jPMLdUB86YMITm3YkP0baSBoB2VIDa5WnUB0Y7gIjXAlqUBgqLhIDx.bkPFdkXBAXRWIjgWIlPhUqjWIjgWIlP5m8UBkqLhITfMfkPcFeXBwVQbClPpvsUBIlOQDlPiloUBIKKgIDd.YkPxxRXBok4UIjXxxRXBgXtUID7kDlP8vXUBI3EgID0fUkPhUJ6fIDmdSkPCdHXB8ZhTIjxW.lPulHUBMVY...";
	
	icons.caretDown = Content.createPath();
	icons.caretDown.loadFromData(pathData);
	
	// Settings - Reza
	pathData = "868.t01M4e7PCBv.Cw17cc7PCBv.CI13Ec7PcSj.CYRHGOjsSFvPGEuwCQJ7.LDaAA1wCAqD.LjXGZ7wCkDi9KTTHe7Psy+9BsIYGOTjsouPhQL.GOTMdiuPLykwCMd43Kzo1W7P46m9Bw1jHV7PKcC+BIFx1T7P+T29BMe2DOTPfquPc9GwCYme5KDac9GwCsdD3KjXc9GwCw0y0KjKMP7Pdo+7B8+eCOjW5OuPhAs7BOjW5OuPAAnvCw0y0KTP.J7PqGA9BwVP.J7P46m9BIFChH7PAAt9BcSxAOzO0suPtdWvC47M7KDa4kPvCkue5KjXyLJvCId43KDW++6Pz3M9BU3l+NTjsouPh45M+NT67uuPYlyuCwLi9Kz2e96PvJA.Cw1NO.7PnEO.CIFWe+6P4PY.CArt+NjGEIvPvJ5uCMH.CLDabRvuCMH.CLjX3OmuCMH.CLTt926PhV9.Ckq+8Nju+SvPhkq+8NjWZXvP3OmuCsy+FLDmD76P67uACwFrh96P67uACIFv596Pep6ACw02+NjwqgvP67.vCcoCILDaIF5uCse5ILjXCsyuCYnsJLDV476Pz3+BC8Rm+Nj3EyvPhUN..ODjM1vPcSJvCkahMLj.KD7PtzKCCwF72E7PSM9BCIVdIG7PYQDCC4jHBOD1NxvPiAnvC06uLLDaiAnvC0l7MLjXiAnvCU6DOLj7xK7Pz3+CCEBfCODM9+vPhAUCDODM9+vP+9GwCU6DOLzu+Q7PsIeCCw1u+Q7P.ALCCIF8cS7Pb9HCCkrMEOTGEwvPygXwCcA4KLDaeTewC8VuLLjXEtkwCoehMLDO+a7PQ2XCCMwXGOzHFyvPhotwGOTc9uvP+S7wCUnsJLTtdc7P7ndBCwFRwa7Pa8PBCI1Igb7PJxFBCQdQGOzX6dvPz20wCw2+FLDaXk+wCw2+FLjXcnHxCw2+FLzN+i7PcogACsy+HOz++SvPhow+HOzWkOvP7mHxCIH.CLzM4e7PBBv.CMVac92vCEW+ILjXQ1gvCEW+ILzk9C7PFD7ACco+.Oj99SvPhco+.Oj67HvPQ1gvCUL..LTm+M7PEC..CIVpgS7PEC..CMJ.FOj67HvPiBfwCou+DLjXiBfwCYPvGLTpgS7Pw0eBC04eCOTb8mvPiUF...";
	
	icons.settings = Content.createPath();
	icons.settings.loadFromData(pathData);
	
	// Add - Material
	pathData = "356.t0lRRHBQsssoCw1ssu.QsssoCE23Kn.QsssoCIewHPjhOQ5PwA.fGPDpCG5P..3ADA..dNTb..3ADcEOZNj7Ei.QzA6kCE23Kn.QRRRkCca6KPjjjT4ProjDhPjjjT4ProjDhPj11F0PwojDhPjhunzP6f0HDQ7EEMTbr3IID4+++LD..ZBQ9++OCEG0ggBQ9++OCY7ooPDwWTzPwca6pPjhunzP21tJDossQMDa21tJDIIIUNDaJIQPDIIIUNTbdPuPDIIIUNzC5PDQzA6kCEG..VDQWwilCA.fEQD..34PwA.fEQDpCG5POnCQDo3SjNTbdPuPD011lNjRRDDQsssoCw1ssqBQsssoCw1ssqBQRRxzCE2ssqBQ5ft0CY7ooPTGzk8PwQcXnPD..v8P..nIDA..bOTbr3IIDA..bOzNXMBQcPW1CEmRRHBQ5ft0CojDhPjjjL8ProjDhPTaaa5PiUF";
	    
	icons.add = Content.createPath();
	icons.add.loadFromData(pathData);
	
	// Edit - Reza
	pathData = "424.t0lii4.QjiiyCw1B1LAQjiiyCwFd2SCQhHthCwlK3ICQNNdgCw16N.CQQDQfCwlii4.QpOIwCwlii4.QjiiyCMVaGGuBDA..bOTbFrWBDA..bOzf8g.Q6Sf1CEG..d.Q0m.1CA.fGPjbbT8PrA.fGPzzmQ7PwA.fGPzYlF7PDQ.BD0wI+NTbHhHBDM8o7NjA6k.QXKrtCwFd2SCQVv9QCEG8oWCQhHBQC8IM2PjDQHzPwoze3PD...zP..dNDA...MTb1BzNDA...MzV.xCQRDgPCEG..2CQhHBQCgHx9PDQDgzProOgCQjNNt0PwMXiDQjKX80PBaPQDIrUjMTb..XQDYUUoMD..VDQtfsaCEG..VDQXK.cCIrAEQzfsj2PwMXiDQjKX42P5S3PDgROANDaT5AFDUeBXOTbWvxED8t6YOjbrWAQ3cu1CEWyrRAQ...2CcASSPD..v8Prcb7JPD..v8Pi0lbb5CQtfsaCwF8ImCQ533VCwlbb5CQtfsaCMVa3cOMDIh3JNDatfmLD433ENDau6.LDEQDANDa3cOMDIh3JNzXkA";
	
	icons.edit = Content.createPath();
	icons.edit.loadFromData(pathData);
  
	// Trash - Material (1.0:0.8)
	pathData = "504.t0F.fLAQ..73CEmls+.Q..73C0roMPjYx78PwA.XKPTyjp8P..1BDA.PTODa..1BDA..eMTbloaBDA..eMzLch.QzrnVCEG..d.QlYgUCA.fGPD..9zPwA.fGPjloizPyzIBD4LcDMTbloaBDA...MD.fs.Q...PCwF.fqAQ...PCEG.fqAQZlVNCMS+aPjyzSyPwYlFcPD..ByP..rGDA.fvLDa..jKDA.fvLTbZV9KDA.fvLTyBDCQNSOMCEG.fHCQZlVNCA.HxPD...zPrA.nAQD...zPwoYQCQD...zPLKFQD4LcDMTb..XQDoY5HMD..VDQ..3SCEG..VDQlYgUCwrXDQDMKp0PwoYQCQD..70P..ZPDA..eMDa..ZPDA.PTOTb..ZPD0LoZOzLY8CQlIy2CEmYRzCQ..73CA.34PD..O9PrA.HSPD..O9Pi0F.fmCQ..vWCwF.fLAQ..vWCwF.fLAQ..D0CwF.fmCQ..D0CwF.fmCQ..vWCMVa..tFDA.vDODa..pHDA.vDODa..pHDA..9MDa..tFDA..9MDa..tFDA.vDOzXsA.XpPD..S7PrA.HxPD..S7PrA.HxPD..32PrA.XpPD..32PrA.XpPD..S7Pi0F.fLAQ..vWCwF.fLAQ..D0CwF.fLAQ..vWCMVY";
	
	icons.trash = Content.createPath();
	icons.trash.loadFromData(pathData);
	
	// Download - Material Icons (1:1)
	pathData = "606.t01x8YBQZFztCEGpZWBQZFztCQhSkPzJVq6PwoYvjPDrpo6PX0CIDshX4NDalYcEDgDkbNTbl4MEDIzlZNTypSAQim+kCE2L2SAQQhUkCgG3UPTjnM4PwEu2VPTj3E4P.XCFDgDbQNTbOzXFDA.ZQNzCEpAQ.f0jCw1UEMBQllOoCw1UEMBQhpNSCE2UEMBQd01QCg8LjPDo1NzPwgkHkPD...zPmKnIDA...MTb0M9IDA...MzCOiBQjZ6PCEGp5lBQd01QCgptoPjnpyzPrgptoPjo4S5Prw2hxPD.XM4PwkBfyPD.nE4PeBMMD0LfQNTbNDhMDoYlQNDhebCQZl3jCEGyHfCQZlWkCEOC3PDeef4Pw8PD3PjWEq4POjwMDIUsbNDanJLJDshX4NTbl4CJDAqZ5NzoudBQqXstCEW6fbBQZFztCsbelPjlAs6Pi0VT02.Q...2CEGtWs.Q...2Cw8ZIPDRnf8PwA.fGPTjPQ8P..3AD4UEOODa..3AD4gT6NTb..3ADw2j3NDftg.QdfqsCEW.ck.QMyMsC8XuJPTybS6Pw4gGLPTybS6P3lPCD4At1NTbQUeCDw2j3NTT02.QdH0tCwVT02.QdUwyCwlqJ7CQdUwyCwlqJ7CQdH0tCEmqJ7CQ7MItC8R9+PjG3Z6PwA64.QTybS6P9fjPD0L2zNTbLi5PD0L2zNjYTRDQdfqsCEG..VDQ7MItCA.fEQjGRs6PrA.fEQjWU77PwA.fEQTjPQ8PjP4PDkDJXOTbHgZPDA..bOjqJ7CQ...2CwVT02.Q...2CMVY";	
	
	icons.download = Content.createPath();
	icons.download.loadFromData(pathData);
	
	// Update - Material Icons (1:1)
	pathData = "1442.t0lK81.Q..fmCEmK81.QJ.5qCArGSPT5wz6PwIEfXPDxCq7PNhMHDQezNOTbFPfHDwZbOOTs2JBQAiWzCEGYqMBQW+2zCQ1ZiPjs9W8PwQ1ZiPjk8g8PG+nHDgMHZOTbpPaHDsAwaODpbBBQQwz1CE2kwVAQJ4t0CsLlNPD.ZW7PwA.fGPzsES6P..3ADA..dNTb..3ADkjNGNzwh5.Q+uDaCEmiEWAQrMhRCAJrfPjWmEzPwEBxgPjx2AzP9NpHDAkuCMTba82HDQMAGMzV+MBQTJ.SCE2V+MBQRAPTCw5xhPjeNT0Pw0+EhPTpbj0PDxNHDkAWZMTbRAHFD8FdhMDvdLAQsvYeCEmK81.Q1+EiC4RuMPD..34Pi01jnlBQByRoCwF9s8BQ4GZlCE2hcACQRK7kCIOrwPjzBe4PwkEAyPjzBe4PrO+LDkenYNTb.NNMDARfaNTgYSCQtehmCEWhOSCQ75LnCY+2yPz3sJ5Pr8OtnPDz6i6PwsVxmPD9Zq6P6mnIDgu15NTbLpTIDgu15ND9ZQBQPuOtCw1DLjAQYXinCE2ebfAQxaEnCsmIXPzFD24PwYGLXPDQwr4PJ.RFD0gTYNTbd9fFDYubWNTBYsAQ1K2kCEGchxAQ1K2kCgfjcPTGRk4PrQ1ZiPjvrT5PrQ1ZiPzLyT3PwQ1ZiPjYLJ3P7CEIDUSv.NTbTZSIDk.68Mz9IZBQIvdeCEmXceBQIvdeCouvnPTMAC3PwMIpoPjYLJ3PShZJDMyLENDaShZJDILKkNzXscDKyPziLj7PwA7UzPTLkd7PhTaMD8QyGOTbDJwMD0P8GOzCVfCQivexCEmnEjCQJs8xCQa23PTHt47PwYbs3Pz8.D8PE44MDUEZROTbk8QMDwtgUOTnjICQmm70CEG2o9BQgyf1CoxwrPTTLs8Pwo6gqPzFDu8PlfoJD8LMZOTbShZJDQXoXOzjnlBQ15e0CE2jnlBQoe0zCQidpPzzPE8PwU8RqPjuI87P77IKDggfNOTb1YkKDQnjMODt4+BQlrByCE29bFCQHOrxCcDKyPziLj7Pi0lJGyBQQuuVCE2vysBQExVVCYBlpPjVdU0PwoHuoPjKPE0PJxaJDQo.LMTbJxaJDgOsFMjHhpBQhY4PCEmtGtBQJeGPCoxwrPjWmEzPwQcuuPjOlOzPSJnLDICaHMTbScTMDgh7LMzLFeCQx72TCEGsciCQt2jUCwZ73PTqKs0PwIZA4PzZIA1PFnBNDs6AjMTbxoyMDYdEnMDDcWCQBWFZCEmq+QCQdVKZCUCUyPj3lW1PwkNwwPza3I1PlFBLDQapeMTbj4mKDgu1bMjJGyBQQuuVCMVaPbqOD8lTpNTbiqwODI5pmNjZn.DQnQeoCEG70DDQtzCoCYUhBQjK8P5Pw0K2CQjK8P5Pd4JQDQDQlNTb..XQDo0RnNDIvTDQ4nrpCEGaPRDQLdKrCQOYCQjGYX6PwoWNBQDr5s6P3XIPD8Fd.OTbIJ9ODI2oBOTFi5CQxcpvCEmpi0CQxcpvC0.h7PDNvC7PwkGl6PTDQ76PFp2NDQjZ7NTbTx0NDY2v4NzPPvCQDx1sCEG3qyCQs2DsCMYk8PzWaD6PwYzO9PDzn25PPbqOD8lTpNzXsMDD7PjiqQ3PwQIW6PDmTH3PFp2NDs3.+MTb4g4ND4c24MTCHxCQO9gcCEmpi0CQbDqbCkwn9PjBYK2Pwkn3+Pz8.L2P3XIPDMxC2MTbx0jPDAUg.Nj53MDQP6fgCE2XjRDQPg4hCsAQEQjnEF4PwA.fEQjfDP4Pd4JQDo53UNTb8x8PDIsvWNjUIJDQRK7kCEG70DDQRK7kCoFJ.QDn2W4PwMtF+PDbrP4PPbqODIZgQNTbF8iODAyENNzjU1CQpBshCEG3qyCQkn3gCMDD7PjiqQ3PiUF";
	
	icons.update = Content.createPath();
	icons.update.loadFromData(pathData);
	
	// Ellipsis Vertical - Font Awesome
	pathData = "3542.t0F..ZBQI2v0CwF..ZBQI2v0CwFc6VBQcdw0CwlY2SBQSTy0CwFUzPBQZX10CwVtxMBQPp50CwlDyJBQKI.1Cwl10GBQQzF1CwVh6DBQfpN1Cw1kDBBQlpW1CwldQ+AQGyg1Cwlnh7AQbBs1CwVf34AQxV41Cw1fS2AQJtF2CwlDzzAQbFU2CwFkZxAQTcj2Cw1ZGvAQTvz2CwV85sAQ37E3CwFi0qAQN.X3Cwlg2oAQc2p3Cw1LAnAQje93Cw12RlAQa0R4CwFzrjAQw0m4Cw1QOiAQPc84Cwlf5gAQXnS5CwVstfAQnSp5CwVDreAQYaA6CwVvxdAQ76X6Cwl5BdAQhwv6CwlpbcAQT3H7CwlF.cAQfLg7CwFSsbAQIp47CwFSjbAQWMR8Cw1GkbAQMxp8CwlwubAQuTC9CwVNDcAQDwa9CwFahcAQPCz9CwlRJdAQaGL+CwFu6dAQu4i+Cw1m1eAQYV6+CwFz5fAQyLI.Dw1HHhAQ1eT.DwlYdiAQjhe.DwlX8jAQGSp.DwV1jlAQ0uz.Dw1hTnAQB29.Dw1KLpAQEmHADwVdKrAQb9QADw1ERtAQm6ZADwFsevAQIciADwF8yxAQrgqADwVdN0AQ7GyADwF3t2AQsN5ADwlvT5AQzz.BDwls+7AQP4FBDwVSu+AQBaLBDwFFiBBQPYQBDw1nZEBQIyUBDwVdUHBQ+mYBDwlHSKBQJ2bBDwlISNBQKfeBDwFBUQBQkhgBDwlSXTBQD9hBDwldbWBQZxiBDwF..ZBQ..jBDwF..ZBQ..jBDwF..ZBQ..jBDwFiDcBQVriBDwllHfBQawhBDwFqKiBQXOgBDw1QMlBQcFeBDwl6LoBQ+VbBDwlIJrBQbAYBDw1cDuBQUFUBDwFZ6wBQRlPBDwlgtzBQAhKBDwlWc2BQW5EBDw1eG5BQLv+ADwFer7BQfD4ADwV6K+BQX3wADw1ZkACQ6LpADwFk3CCQaChADwlBEFCQJcYADw1bJHCQdaPADwVdHJCQ2+FADwVy9KCQyK8.DwVHsMCQ3.y.DwFLSOCQsfn.DwFtvPCQ9rc.DwleERCQZmR.Dw1RQSCQxQG.Dw16STCQxa2+Cw1OMUCQP6e+CwlE8UCQqEH+CwlUiVCQ29u9Cwl4+VCQrpW9CwFsRWCQCM+8CwFsaWCQ1ol8CwV3ZWCQ.EN8CwlNPWCQch07Cw1w6VCQGFc7CwFkcVCQ6yD7Cwls0UCQwur6CwVQDUCQb8T6CwVXITCQyf85CwFLESCQjcl5Cwl22QCQd2O5Cw1lgPCQEx44Cw1mBOCQ8Pj4CwFJaMCQfWO4CwlcqKCQHI63CwlzyICQ.om3CwFhzGCQR5T3Cwl5sECQ8+B3CwVSfCCQ47w2CwVCLACQyyg2CwFhw9BQRmR2CwVHQ7BQvYD2Cw1Oq4BQfM21Cw1R.2BQoDq1CwFsPzBQFAf1CwV5bwBQoDV1CwlWktBQ3PM1CwFhpqBQLmE1Cwl2rnBQ0H+0Cw11rkBQy140CwF9phBQ+w00Cw1rmeBQA6x0Cw1gibBQVRw0CwF..ZBQI2v0CwF..ZBQI2v0CMVa..nIDYAi9MDa..nIDYAi9MDazsaID46m9MDalcOIDwp19MDaTQCIDgKO+MDa4J2HDUZw+MDaRLqHD0nN.NDaZWeHDQUo.NDaItSHDItHANDaWRHHDgtrANDa5E8GDoPUBNDahJxGD4MBCNDaAhmGDQeyCNDaCNcGDw7nDNDaRPSGD4chENDaTpIGDY4eFNDaqc.GDcEgGNDa0q2FDs2kHNDaLVuFDAEtINDaFdmFDAh4JNDayDfFDcBHLNDaeKYFD4YYMNDaPyRFDQasNNDaG8LFDI4CPNDaBpGFDokbQNDa05BFDsR2RNDaQv9EDswSTNDaAK6ED4ywUNDapK3EDQJQWNDapx0EDckwXNDaZ.zEDI1RZNDaL0xEDsrzaNDaLQxEDg4VcNDaeTxED8L4dNDaF+xEDIWafNDa4PzEDcH8gNDarI1EDMQdiNDaJo3ED0g9jNDa7t6EDIqclNDaeZ+EDsc6mNDaPqCFDgpWoNDaifHFD8BxpNDal4MFDkXJrNDah0SFDEcfsNDaYSZFDwBztNDaKRgFDY7DvNDauvnFD07RwNDa4svFDo2cxNDaWH4FDAgkyNDaz9AGDQsozNDazOKGDkQp0NDa44TGDsCm1NDaf6dGDw4e2NDaBSoGDspT3NDa19yGDMNE4NDaM89GDYbw4NDaXLJHDMNY5NDaipUHDUc75NDa4UgHDADa6NDahLsHDc8z6NDalL4HDkEJ7NDaHTEID0XZ7NDaNgQIDszk7NDa5wcIDYWr7NDa..nIDMDt7NDa..nIDMDt7NDa..nIDMDt7NDaLRzID8lq7NDaZh.JDgOj7NDartLJDI+W7NDaG0XJDw2F7NDatyjJDE7v6NDalnvJDoOV6NDa2Q7JDw115NDansGKDc1R5NDaF5RKDUTp4NDad0cKDAW83NDa+cnKDsEL3NDa7wxKDInV2NDasu7KDEGc1NDaqUFLDkqe0NDaThOLDgedzNDaJTXLDUsYyNDayofLDAfQxNDa4gnLDECFwNDaM6uLDgh2uNDagz1LDMKltNDavL8LD0IRsNDa3BCMD4q6qNDa9UHMDY+hpNDaKEMMDYRHoNDauOQMDUyqmNDa+zTMDIwMlNDaVzWMD0ZtjNDaVMZMDo+MiNDal+aMD4trgNDazJcMDU3JfNDaztcMDgqndNDagqcMDIXFcNDa5.cMD8MjaNDaGuaMDobBZNDaT1YMD4SgXNDa1VWMDICAWNDaEQTMD44gUNDagkPMDYGDTNDavTLMDc5mRNDadeGMDAhMQNDaaFBMDgL0ONDaeJ7LD8GeNNDanr0LDQhKMNDa1stLDon5KNDaROmLDInrJNDaHReLDQsgINDap2VLDADZHNDaMANLDs2UGNDaMvDLDYSUFNDaHF6KDQgXENDagDwKDMqeDNDa+rlKDM5pCNDaKAbKDwV5BNDazBQKDgHNBNDaoyEKDsVlANDadU5JDoGCANDaHptJD4fj.NDadyhJDcmJ.NDaayVJDs9p+MDa3qJJDMXJ+MDayd9IDYfy9MDaGNxIDEal9MDa..nIDYAi9MDa..nIDYAi9MzXs4H20PzztwvPr4H20PzztwvPrQ500PDobkvPrgNx0PDaLYvPrYFr0PjH.MvProhi0Pzs4.vPr0jX0PDN1ouProNK0PjcLRuPrMh6zPj745tPrAhozPzXBjtPr8PUzPDcoMtPrUx9yPTtx2sProIlyPjrghsPr4ZKyPDw4MsPrUptxPzN94rPrk7OxPzRxlrPrgVuwPj.YTrPrc8LwPjT0BrPrw1nvPDCJxqPrQHCvPT1YhqPrE3auPDPmSqPrULytPDmzEqProKItPDID4pPrs7csPj3WspPrclwrPzrwhpPr4ODrPzRSYpPrY.VqPjK9PpPrU+lpPDryIpPrIT2oPD9zCpPrgFGoPD9B+oPrMdVnPzcd6oPr4hkmPTAH4oPrcbzlPz..3oPrwRClPDnF3oPrsMRkPj0a4oPrAUgjPDb+6oProvviPDAw+oPrQn.iPD9uDpProCQhPTf6JpPrYJhgPDnRRpPr8CzfPjJzZpPrs2FfPzudjpPr8rZePT0PupPrspudPjrH6pPr02EdPDbDHqPrAaccPj+AVqPr0Z1bPjG+jqPrY8PbPja4zqPrsHsaPDXtErPrkBKaPjQaWrPrYvpZPDR8orPrYWLZPjbQ8rPrU7uYPjpTQsPr0iUYPjuClsPrIR8XPjVa6sPrAKmXPTEXQtPrIRSXPjZ1mtPrkpAXPjvx9tPrMWxWPzbIVuPrgZkWPTu1suPrc1ZWPDa6BvPr0rRWPz8BOvPr49LWPjCPavPrksIWPTufmvPrI2HWPzztwvPrI2HWPzztwvPrI2HWPzztwvPrwEJWPj.A9vPrgwMWPzNQJwPrs4SWPzgcVwPrYcbWPj7ihwPrMamWPjihtwPrcwzWPDbW5wPr4cDXPDs.FxPrEdVXPzdbQxPrIupXPz7nbxPr0MAYPTTjmxPrg1YYPj0LxxPrQkzYPjyf7xPr0UQZPjjdFyPrkCvZPjhDPyProoPaPjKQYyPrwByaPTAChyPrcIWbPzoXpyPr427bPDvPxyPrIHjcPDCp4yPr0yLdPjWi.zPrgz1dPTl6FzPrgChePjtwLzPrwYNfPTzDRzPrQv6fPz.zVzPrw+ogPjj9ZzPr4.YhPDzidzPrErHiPDKigzPro43iPDK7izPrAhojPDatkzPrQcZkPDo4lzPrsiKlPzncmzPrYs7lPTUZmzPrgxsmPjtulzPrIqdnPT6ckzPrgOOoPjHkizPr4W+oPzoEgzPrg7tpPz3+czPrw0cqPzTTZzPrM7KrPjiCVzPrYH4rPzPNQzPrMSksPDN0KzPrcUPtPTR4EzPrUH5tPjZa+yPrEkhuPznb3yPrUkIvPjD9vyPrwBuvPz5.oyPrY2RwPjblfyPrg8zwPz+uWyPrsOUxPT+dNyPrsnyxPT5zDyPrwCPyPDSy5xPrQbpyPzvavxPr8sBzPT8ukxPrE0XzPzkwZxPr8srzPDahOxPrgU9zPDPDDxPr0nM0PD5X3wPrkkZ0PjPhrwPrkIk0PDMhfwPrMSs0PjpZTwPrIAy0PzjMHwPrgR10PD476vPr4H20PzztwvPr4H20PzztwvPiUF";
	
	icons.ellipsisVertical = Content.createPath();
	icons.ellipsisVertical.loadFromData(pathData);
	
	// Question - Reza
	pathData = "974.t0VJTWzPm.3FBIFCRVzPm.3FBUBVEMTk7tgPXZRQCkIMbHjXKTOQCwIqbHjUOSzPkQTGBwWsDMjI62gPhI5lDMDSx5gP45HQCwlYeHTtNRzP8gAHBIVtNRzPh6FHBEukDMDX+BhPxbJQCITBgHjX5cKQCY0TgHzfKSzPhgWHBIz3DMjX3EhPhk2BEMjX3EhPGaRQC4lCgHTI0TzPaoCHBIlaDUzPa+1GBEwUEMTJV6gPazVQCseadHjXkLXQC0bAdHzhkVzPfGcGBkB0EMD3Q2gPhA+9EMD3Q2gPxwgQCIVAdHTp0XzPjwlGBIF3NYzPXNsGB00VFMDNR8gPcskQCUE5eHjXcskQCkUMfHTXWYzPwwGHB8vSFMjG9BhPhgsQFMDy+ChPCxiQC04NgHDfvXzP5CWHBIFYjXzPHZZHBENDFMzH1GhPCWeQCowWhHjXUacQC0w0hHTS9VzPg6yHBMAqEMDPVNhPhkclEMDasOhPmrXQComTjHDJ.VzP9WLIBI1G0UzPPkSIBA7aEMD0AWhP.+VQCE4WlHjX.+VQCIW2lHTO2UzPBvyIB4igEMzt6chPh4SkEMDc6dhPDeZQCI31mHjy8VzPBt8IBIFNnWzPBt8IBYW.FMTI5chP4kfQCEtslHjXo3fQCQvVlHDlQXzPIogIB09DFMDu0WhPhoiEFMDLQWhPDlgQCEOqkHzscXzPxfXIBI18gXzPxMVIBIHJFMj+5ThPpDiQCQvCkHjXQmiQCkv3jHjYEYzPi.KIBI8TFMjE1QhPho9gFMDemNhPJvpQCgGEiHzJ.azPK0qHBIFQTazPdXlHB4Z4FMDJ9GhPKQuQCQhggHjXoKvQCEhCgHzGJbzP7JHHB8gBGMzBi+gPhshBGMjHY7gPp0uQCMUWdHTviazPJBaGBIVMJazPxOPGBUaoFMja6wgP.amQCcuEbHjX8djQCEqraHjkQXzPm.3FBkB0EMzI.tgPi0VrxVzP5CVJBIFPXVzP7LVJB8bfEMzbHlhP88VQCgRzoHjXExUQCkFGpHzBSUzPsimJBsvTEMT9lqhPhsvTEMT4hshPFyUQCgwvqHjZvUzPke.KBIFCDVzPyxDKB0vlEMTEuwhPVUaQCUwarHjXB6bQCUwarHDIkWzPqwDKBoH9EMz0FvhPhU9BFMDDAuhPkVgQCsIXqHToUXzPwYtJBIVoUXzPlgmJBAFCFMTZbnhPcmeQCgRzoHjXAcdQCsjgoHzTPWzP5CVJBQSsEMj9fkhPhgEsEMj9fkhPKNaQCcNXoHTrxVzP5CVJBMVY...";
	
	icons.question = Content.createPath();
	icons.question.loadFromData(pathData);
	
	// Question circle - Reza
	pathData = "1194.t0F.xixP..kEBIlvHbxP++jEBAndkLDBKxgP.pWICA.LjHjX.pWICkO0qHjvHbxPA3fLBAf7nLD.NHiPh4y1pLz+MHiP.nFKCgO0qHD.pwxP..CIBIF.pwxPIrHGB4y1pLT.PYgP.HOJCA.TVHzXsAf7nLD.1igPhs6epLT.1igP.B7JCcQ9cHDf.uxP..CIBIFf.uxPoalJBs6epLz+m8hP.HOJCA.ZuHjXFQ1ICE.ZuHD.jXxPpalJBA.IlLD.vPhPhE.IlLjE42gPFQ1IC8e8XHD.xixP.XOFBMVaHmOJCc6saHjXqdKJCc6saHj48gxPmP+FBkESnLTJrwgPhwrFnLDKjygP0S+ICU+dcHzFaexP2JiGBIVPAexPcmtGBoGsmLT+c9gP5Q6IC0.TfHjX5Q6ICImofHTj7dxPvaOHBIMymLjz.EhPhoQ2mLT4JFhPiD+ICI+qgHj3HfxPx+ZHBIlFwfxPx+ZHBkHSnLj+EEhPmqEJCsdbfHjXunFJCw1oeHDr7gxP41vGBoqjnLzhk5gPhULpnLTW83gPprLJCAWBdHDx4ixPvkfGBI1igjxPvkfGBEgPoLj773gPHsUJCQ+ndHjX+QWJCgxBeHjGAlxPOo3GB4QfoLDaf.hPh4QfoLDbsAhP+yWJCgHsfHTqzkxP0XOHBIVcrkxPieSHBUjXoLTKyEhP+XUJCkHpgHjXinTJCcg2gHze1jxPy1hHBA1FoLTpVJhPhEG+nLDqNLhPpONJCAmciHDrQixPO27HBIlc+hxP6SBIBUNrnLDBJRhPlWJJC0X+jHjXcqIJC8MbkHDWUhxPikeIBwUknLDHWZhPhwUknLT.UbhPbyIJCE4bmHT2qhxPJM6IBIV25hxPCL+IBMVynLDDSfhPsMNJCAwDnHjXW2PJCAwDnHjEmjxPyF6IBkwKoLzatahPhg7LoLjjRZhP1bSJC4kTlHzh4jxPQ2hIBIV16jxPEkfIBAxOoLzejWhPRMTJCA7ukHjXRdTJCAvlkHDHNkxPMJWIBcrUoLjjFUhPh41WoLzkZThP.rVJCA64jHDb4kxPj1JIBI1gslxPJ78HBcZzoLjALMhPIWdJCgM8hHjXhmeJCwZmhHDSKnxP0ViHBkdFpLTr8FhPhcHJpLjqEEhP+9hJCkjtfHzuunxPWpAHBI1xunxPtB0GBwvHpLz2T5gPhkfJCYA5cHjXV+dJC82NcHTUKmxP5KKGBAFmoLzfNwgPh4UaoLjOpugP1bSJCM6saHTx4ixPyd6FBMVaPgMJCoHloHjXe2KJCsrloHjamhxPD.bJBwQknLTtHnhPhQhfnLj9SohPphGJC4GrpHjp3gxPI5wJBIlp3gxP0o4JBQlfnLDp5uhPHXIJCY2OrHjXqlJJCMDgrHzp.ixPlZJKBUu1nLjolxhPhEF8nLjolxhPCqPJCw+frHTJdjxPm4CKBIFgwjxPgh+JBQzNoLzJXthPDsSJCIfGqHjXDsSJCc+qpHD.xjxP5OkJBw2GoLjtHnhPhANCoLT28lhPxWOJCsHloHzzZixPKhYJBIlCZixPKhYJBoT1nLDdXlhPDgMJCsHloHzXkA..";
	
	icons.questionCircle = Content.createPath();
	icons.questionCircle.loadFromData(pathData);
	
	// Info - Reza
	pathData = "353.t0F..PfP...CBwF...fP...CBwF...fP...zAIF...fPBrxwA4O03GD...bP...7AA...GDa...3AA...GjXBrx0AA...GD...cPBrxwAA..PGD...cPhA..PGj+TicPBrx0AA..fGD...dP...3AwF...dP...CBwF..fcP...CBIl.q7bP...CBA..HGTfU9fP...xAA..THjX...xA8mZXHj.q7bP...GBA..XGD..vgPrA..DHD..vgPh8mZHHD..vgP...CB8mZXHD..vfP...EBIF..vfPAV4CB8mZHHD..vfP...ABA..LHzXsA..rGD...aPhoDC2GD...aP....BoDCmFD...fP...mAIF...fP1NOjAoDC2GD..fXP...6AA..HFjX1NO3AA..HFD..fcP1NOjAA..XGD..vYPhA..XGjRLbZP1NO3AA..vFD..vdP...rAMVY...";
	
	icons.info = Content.createPath();
	icons.info.loadFromData(pathData);
	
	//! Info circle - Material (1:1) 
 	pathData = "750.t0F..ZBQ..PuCEGRQeBQ..PuCEWsnPjq2r6PwoYloPDWuk6PZlYJDwLy1NDaZlYJDA..dNTbZlYJDAWWaNTb0hBQdTYlCEGRQeBQLy7kCA.flPDyLe4PwgqKkPDyLe4PPpDID4QkYNTblY1HDAWWaNjYlMBQ..fmCwlYlMBQLyrsCEmYlMBQb8VtCAoRjPjq2r6PwgqKkPD..z6P..nIDA..8NzXsA.flPjYls3PwgTzmPjYls3PwUKJDQgmINTbZlYJDIb0GNjlYlBQyLSgCEmlYlBQjBofCEWsnPjTHC3PwgTzmPz++22P..nID8++8MTb35RID8++8MDjJQBQRgLfCEmYlMBQjBofCYlYiPzLyT3PwYlYiPjvUe3PPpDIDQgmINTb35RIDYlYKND..ZBQlY1hCMVa..nIDA..bOTbHEAHDA..bOj8noAQT3w0CEGo.SAQnvizCgTjPPDbcm7PwwdXLPDt9E7P1CeBDQgK1NTb..3ADAW2pND..d.Q..fmCEG..d.QOJRjCYO7IPz5QW3PwwdXLPjiBT2PHEIDD4QQjMTbjBLED05gSMj8noAQVObRCEGRQ.BQ...PCA.flPD...zPwgq6rPD...zPJboLDY8vIMTbb8CND05gSMDttwCQdTDYCEWEdBDQNJPcCovCCQz5QW3PwA.fEQzihD4P..XQDA..dNTb..XQDAW2pNjBOLDQT3hsCEWEdBDQ35WvCgqa7PDbcm7Pww0O3PDJ7H8PJboLDQgGWOTb35NKDA..bOD..ZBQ...2CMVa..nIDkYlOOTbPJNLDkYlOOjqWfCQb8RvCEWyL8CQdTrrC0LS+PD..34Pw0LS+PT35j3PtdANDcTn0MTbPJNLDwLyXMD..ZBQLyLVCEWbcvAQLyLVCIE5TPzQgV2PwMyrMPT35j3PyLaCDA..dNTbyLaCD4QwxNjTnSAQb8RvCEWbcvAQYl4yCA.flPTlY97Pi0F..ZBQ..fmCMVY";
 
	icons.infoCircle = Content.createPath();
	icons.infoCircle.loadFromData(pathData);
	
	// Warning - Reza
	pathData = "242.t0F..fdP...EBIl.q7cP...EBA..XGTfUdgP...1AA..bHjX...1A8mZfHj.q7cP...IBA..nGD..PhPh4O0vGD..PhP...9A8mZfHD..feP...GBIF..fePAV4EB4O0vGD..PgP...5AA..THzXsULHnGjpweYPhc7ReGjpweYPECB1AwJGeFTwffcPpF+oAwVwffcPUi+.BIVwffcPZQFBBc7ReGT03ufPECB5AUM9KHjXCWO7Asc9KHTwffePTMFBBULH3GT03OfPrULH3GjpweZPhULH3GDqb7YPCWO7AoZ7WFTwffdPpF+kAMVY...";
	
	icons.warning = Content.createPath();
	icons.warning.loadFromData(pathData);
	
	// Warning circle - Reza
	pathData = "462.t0VzMMyPgNdJBI1bWLyPgNdJBM05xLDHTphPSstLCcYaqHjXSstLC4vQrHzbWLyPMdOKBEcSyLTi2yhPh8BgyLTi2yhPNA6LC4vQrHjSvNyPW11JBIlSvNyPfPoJB8BgyLTnimhPQ2zLCE53oHzXsYoSyLTmHvgPhgCFyLTmHvgPXvtLCwQtbHDFrKyPSJYGBwFFrKyPU4rIBIFFrKyP+e5IBgCFyLzRXghPV5zLCsDVnHjXyS3LC0GVnHzDwNyPMe5IBMQryLTUNahPrMQryLzjR1gPhMQryLDG4xgPyS3LC0IBbHjkNMyPch.GBMVaS3zLCAfnVHjXTSVLCAfnVHzjV+xPHrMGBMo0uLD..RhPhMo0uLD9jvhPUSVLCAfWxHzDNMyP.3kLBIVT2TyP.3kLBMgw1LD9jvhPSXrMCA.fjHjXSXrMCgv1bHTT2TyP.HpEBMgSyLD.hZgPi01DNMyP.XTFBIVyaSyP.XTFBMIG1LzEI4gPSxgMCA.fjHjXSxgMCktspHTyaSyP.n6KBMgSyLD.59hPhgEvwLD.59hPS.HLCktspHzD.ByP..HIBI1D.ByPWjjGBgEvwLD.FkgPS3zLCAfQYHzXkA..";
	
	icons.warningCircle = Content.createPath();
	icons.warningCircle.loadFromData(pathData);	
	
	// Warning triangle - Reza
	pathData = "1513.t01+4dnPmFckBIlbncnPmFckBMjIGJj0SXoPCYxgBMVYVJjXCYxgBAusVJjbncnPejukB8etGJzG4aoPhw3BHJzG4aoP61DhBAusVJztMgnPiUlkBI1tMgnPVOgkBw3BHJzoQWoP+m6gBcZzUJzXswxtGJjgeBoPh8YZGJjgeBoPvcxgBUa3PJDbmbnPBMSjBwFbmbnPqlJkBIFbmbnPKsOkB8YZGJzY8ToPrr6gBcVOUJjX4x.hBoWOUJD5NgnP3rOkBgtSHJzpoRoPrgtSHJjPyDoPhgtSHJTsgCoP4x.hBY3mPJDK6dnPF9IjBMVaop6gBobnKJDaop6gBobnKJDaxH6gBIfnKJDaAm5gBUpnKJDaZE5gBU6nKJDaDj4gB8RoKJDaCC4gBQwoKJDadh3gBIVpKJDaXB3gBcAqKJDa3h2gBIyqKJDaBD2gBAqrKJDa6k1gBEosKJDanH1gBAstKJDaMr0gBw1uKJDavP0gBEFwKJDaU1zgBwZxKJDa+bzgBszyKJDazDzgBgS0KJDa1sygBE21KJDaIXygBEe3KJDaxCygBUK5KJDaxvxgBg66KJDaafxgBAm8KJDaafxgBAm8KJDaskAfBUpKXJDaskAfBUpKXJDagUAfBUgMXJDa1FAfBYaOXJDat4.fBQXQXJDaKt.fBoWSXJDaOj.fBIYUXJDa5a.fBcbWXJDaPU.fBQgYXJDaPP.fBMmaXJDa7L.fBEtcXJDaTK.fBU0eXJDaXK.fB07gXJDaIM.fBEDjXJDakP.fB4JlXJDasU.fBwPnXJDafb.fBgUpXJDa7j.fBsXrXJDaAu.fBAZtXJDar5.fBMYvXJDa7GAfB0UxXJDatVAfBsOzXJDaAmAfBcF1XJDax3AfB042XJDa8KBfBco4XJDaffBfBIU6XJDaX1BfBk77XJDafMCfBge9XJDa1kCfBs8+XJDaU+CfB8VAYJDa5YDfB8pBYJDae0DfBg4CYJDaAREfBgBEYJDaauEfBoEFYJDaoMFfB4BGYJDakrFfB84GYJDaKLGfB0pHYJDaUrGfBQUIYJDa9LHfBQ4IYJDaBtHfBsVJYJDaaOIfBcsJYJDaCwIfBg8JYJDa0RJfB0FKYJDacxJfBcIKYJDacxJfBcIKYJDa0hriBcIKYJDa0hriBcIKYJDarDsiB8EKYJDaclsiBo6JYJDaDHtiBopJYJDaZotiB8RJYJDaZJuiBkzIYJDa+puiBsOIYJDaEKviBUjHYJDakpviBkxGYJDaaIwiBo5FYJDagmwiBk7EYJDazDxiBk3DYJDaNgxiBwtCYJDap7xiBYeBYJDaEWyiBoJAYJDaZvyiBwv+XJDakHziB4Q9XJDaieziBQt7XJDaN0ziBMF6XJDakI0iB8Y4XJDajb0iBwo2XJDaHt0iB800XJDaM90iBs9yXJDaxL1iBcDxXJDazY1iBYGvXJDaPk1iB4GtXJDaFu1iBQFrXJDaT21iB0BpXJDa381iB88mXJDavB2iB42kXJDa9E2iBEwiXJDaeG2iBsogXJDaTG2iBQheXJDacE2iBAacXJDa4A2iBQTaXJDap71iBcNYXJDaw01iB0IWXJDaNs1iBsFUXJDaCi1iBgESXJDaQW1iBgFQXJDa6I1iBAJOXJDaB60iBUPMXJDaCs0iBUpKXJDaCs0iBUpKXJDa2zDhBAm8KJDa2zDhBAm8KJDaMiDhBcy6KJDaGPDhBkC5KJDap6ChBoW3KJDa2kChB4u1KJDazNChBoL0KJDai1BhBMtyKJDaHcBhBoTxKJDanBBhBU.wKJDaFmAhBYwuKJDanJAhBAntKJDaQs.hBgjsKJDaGO.hB4lrKJDaMv+gBYuqKJDapP+gBM9pKJDahv9gBUSpKJDa5O9gB4toKJDa3t8gBEQoKJDagM8gB44nKJDa4q7gBYonKJDaHJ7gBoenKJDaop6gBobnKJDaop6gBobnKJzXskptGJjqc1nPrk4nMJz+YeoProazAJz+YeoPiUF...";
	
	icons.warningTriangle = Content.createPath();
	icons.warningTriangle.loadFromData(pathData);	
		
  	// Error circle - Reza
  	pathData = "506.t0F.V5wP.fhEBIVvrxwP.fhEBAnGaLDBiwgP.5wFCA.BjHjX.5wFCgOqqHjvrxwP.XdLBAfkdLD.lGiPh4yefLD.lGiP.1fHCgOqqHDfMHxP.f.IBIFfMHxPHLFGB4yefLD.nXgP.XoGCA.JVHzXsAfkdLD.NigPho6HfLD.NigP.RVHCcQzcHDfjExP.f.IBIFfjExPo6iJBo6HfLD..8hP.XoGCA.PuHjXEgPGCA.PuHDfGuwPo6iJBA3waLD.HPhPhA3waLzEQ2gPEgPGCAfyXHD.V5wP.3LFBMVav+.HCo6GdHjX8m9GC49gcHDar9wPteXGBomgeLjte3gPrAfkdLjzgGhProWocLjte3gPhc3ecLj6G1gPCHTGC49gcHDAbzwP59gGBIVD1ywPFdqGBEg8bLDxs9gPDvQGCIVQfHDaJxfGCo2AjHDaDvQGCAVxmHjXQXOGCwRXnHTD1ywPtcUJBQ.GcLjNumhPhcePcLjAGphP68WGCYvgpHjdk1wP57dJBwF.V5wPhzhIBwldF9wP57dJBIFar9wPFbnJB0e5eLjAGphPv+.HCoy6oHjXWWCHC41UoHz00.xPrDFJBQ9CfLjjIehPro1GeLjdGPhPrQ9CfLzjEAhPhQdMfLzws9gPjWCHCU3sdHD7O.xP49gGBMVY...";
  
	icons.errorCircle = Content.createPath();
	icons.errorCircle.loadFromData(pathData);
	
	// Search - Material (1:1)
	pathData = "414.t0FJt4AQfh6tCEWMQSAQfh6tCoIJNPDam45PwA.fGPzMVD5P..3ADAE2MNTb..3ADQMQ0Mjln3.QpIpVCEWMQSAQ...PCghadPD...zPwswBnPD...zP1NqKDolnZMTbPwUMDQMQ0MDTbUCQPwciCEGTbUCQi7YkCoCHzPzK.x4PwQB4xPzNgM5PHYLLDI9pnNDaldHQD0oKPOTb..XQDE0GROD..VDQz6Q0CEG..VDQW5A1CY5gDQDSOn8PwwziCQD..v8P58fPDA..bOTbn9HPDA..bOjSW9CQL8f1CwV7UuBQPxnrCEWmvjBQIgrsCcAvkPTc.k6PwE4ShPDn3t6Pn3lGDAJt6NzXsghadPTNb15Pwg2BkPTNb15PJyZJDUYVjNTbb3jKDIuEaNDGN4BQPwciCEGGN4BQvFJfCoLqoPzE951Pwg2BkPDz3v0Pn3lGDAMNbMTbXC8EDAMNbMjguLAQW3qaCEGMN5.QvFJfCQiiNPDTb23PwQiiNPj7Vr4PF9xDDUYVjNTbXC8EDkCmsNDJt4AQ4vYqCMVY";

	icons.search = Content.createPath();
	icons.search.loadFromData(pathData);

	// Folder - Material (1: 0.8)
	pathData = "202.t01Ly1.QYl4yCE2djr.QYl4yC4iTIPjG0u7PwA.fGPDoPg7P..3ADMyLCODa..3ADkYlwMTb..3ADcqWmMjORk.QBWAXCE2djr.QLyLVCMyrMPDyLi0Pr0LSfPDyLi0PrA.flPTlYF2Pr0LS+PTlYF2PwY31AQTlYF2PC25PD4n33MTb..XQDIbE.ND..VDQyLSgCwF..VDQyLyvCEG..VDQjBExCMbqCQjG0u7PwY31AQTlY97PMyzODkYlOODayLaCDkYlOOzXkA";

	icons.folder = Content.createPath();
	icons.folder.loadFromData(pathData);

	// Open in browser - Material
	pathData = "347.t0lii4.Q...2CE2ELt.Q...2CsfgIPj5ye8PwA.fGPzzmO8P..3ADQNNNODa..3ADoiiaMTb..3ADwELPMzBFl.QtfARCE2ELt.Q...PC43XNPD...zPrIGm9PD...zPwk9bAQD...zPzm2PD4BFHMTb..XQDwELPMD..VDQ533VCwF..VDQjiiyCEG..VDQSe9zCQedCQj5ye8Pwk9bAQD..v8PxwoODA..bODaUUMLDA..bODaUUMLDQNNNODaxwoODQNNNODaxwoODIGG2MDaNNlCDIGG2MDaNNlCDQNNNODappBGDQNNNODappBGDA..bODaNNlCDA..bOzXskiCiPD..v8PrkiCiPjHhF6PrA1hcPzzmx6PrQNtXPzppJ6PrA.flPjbbb4PrwwQzPzppJ6Pr8IcuPzzmx6Prcb7oPjHhF6Prcb7oPD..v8PrkiCiPD..v8PiUF";

	icons.openInBrowser = Content.createPath();
	icons.openInBrowser.loadFromData(pathData);

	//! Open in new - Material
	pathData = "624.t0lii4.Q...2CE2ELt.Q...2CsfgIPj5ye8PwA.fGPzzmO8P..3ADQNNNODa..3ADoiiaMTb..3ADwELPMzBFl.QtfARCE2ELt.Q...PC43XNPD...zPrkiCiPD...zPwoOgjPD...zP8IXIDwf8CMTb..nIDYA6GMD..ZBQbbbSCEG..ZBQhH5TC0mfkPjKXd0PwoOgjPjNNt0P43vHDoiiaMDaNNlCDoiiaMDaNNlCDQNNNODaxwoODQNNNODaxwoOD433jNTbxwoODwf8gND8Y9CQFr+mCEGdWBDQ..fmCkiCBQD..34PwoOgCQD..34P8IHQDYv9eNTb..XQDwf8gND..VDQNNNoCwF..VDQjiiyCEG..VDQSe9zCQedCQj5ye8Pwk9bAQD..v8PxwoODA..bODaNNlCDA..bOzXsIGm9PjKX61PrgR+fPzppJ6PwopBfPToOR6PoOoGDU5izNTbnzQGDU5izNjppvAQqpprCEWK3rAQvVLrC0BNaPjKX25Pw0BNaPzppq5PppBGDAaAoNDazmbNDoiiaMDaUUMLDoiiaMTbT50KDoiiaMTDg4BQtf4UCEmii0BQhH5TC43XsPDGG2zPw43XsPjErezPQDlKDwf8CMTbT50KDA...MTUUCCQ...PCwVNNHDQ...PCEm9DNDQ...PC0mfDQDC1OzPwA.fEQjErezP..XQDwwwMMDa..XQDYUUINTb..XQDgsPLNTeBRDQd2iiCEm9DNDQjiCjCkiCBQD43.4Pwg2k.QD43.4Pzm4OD4cONNTbxwoODgsPLNjbb5CQVUUhCwlbb5CQtfsaCMVY";
	icons.openInNew = Content.createPath();
	icons.openInNew.loadFromData(pathData);

	// Save
	pathData = "420.t0lT3xXPOJbY.IVEtlXPjBWS.oYlEFD...DPovUfAA...ADa...n.A...AjXBWOd.A...AD...DPZlYd.A...AD...JPrA...AD..fYPhA...ATyLCZPZlYd.A..nFD...JP...pAwF..fYP...pAIVyLCZP...pAA..nFTyLCZP...pAA..XFDa...pAw0i5CjX...pAoYloCD6QYZPtdT1.45QiFDov0LPrIEtLFDjBWFPi0F...TP...lAIFovURP...lAA..PDjqG0XP...DAA...FjX...DAQJbkEDovURP...TAA...ED...UPhw0iZED...UP...bAQJbkED...WP...fAIF...WPtdTiAw0iZED..fYP...PAA..XFzXsA..PED...QPrA..fCD...QPh0Ly7BD...QP...n.oYlADD...JP...3.IF...JPLyLu.0Ly7BD...JP...3.A..fBDa...TAA..fBjXZlYXAA..fBD...WPMyLu.A..vED...NPhA..vEjlYFPPZlYXAA..PDD...UP...DAMVY";
	
	icons.save = Content.createPath();
	icons.save.loadFromData(pathData);
	
	// Libre Wave logo
	pathData = "1199.t0Fv1w+P.jTACwFv1w+P.PZkCwFPyuAQ.PZkCwFPyuAQ.nPfCwF3Kp.Q.nPfCwF3Kp.Q.jTACwFv1w+P.jTACMVafmCHDAPRELDafmCHDA.oUNDa.nHKDA.oUNDa.nHKDAPRELDafmCHDAPRELzXsARhyPD.IUvPrARhyPD.jV4PrAbxHQD.jV4PhU7tRQD.jV4PfBRVDwCoLNDnfjEQ.3MeCIFnfjEQKq7YCcv2UQTp2b0P.eLTDAH8RMjXymQUDY29MMD.SeEQLJ.PCAvzWQDfx7xPhAvzWQzheVwP2tYTDAPRELDfleDQ.jTACwFHINCQ.jTACMVa.MiWDAPRELDa.MiWDA.oUNDa.OnZDA.oUNDa.OnZDAng9MDa.aPbDAng9MDa.gncDA.oUNDafAjfDA.oUNDafiAeDAfC0MjXWwDfDY02pMDbJFHQ8+MVCAmhARDf+.zPhAmhARj0XpwP9.KeDAPRELD.OFGQ.jTACwFPy3EQ.jTACMVavwHgDAPRELDavwHgDA.oUNDav3bkDA.oUNDav3bkDAjrBNDaPRqhDAjrBNDaPRqhDA3FqMDafCHkDA3FqMDafCHkDAHNEMDaPRqhDAHNEMDaPRqhDA.KqLDavIXkDA.KqLDavIXkDAPRELDavwHgDAPRELzXsAIFWRDfEVvPrAo8cRD.jV4PrACChRD.jV4PrAXtlRD.16xPrA4UqRD.jV4PrAMcuRD.jV4PrAuT1RDfEVvPrAROxRDfEVvPrAFhsRDv+O3PrAEwnRDfEVvPrAB2jRDfEVvPrA5GfRDv+O3PrA6VaRDfEVvPrAIFWRDfEVvPi0F3h1KQ.VXACwFnLRKQ.PZkCwF3ohKQ.PZkCwFn+oKQ.3AgCwFHeRLQ.3AgCwFD0YLQ.PZkCwFL3pLQ.PZkCwFL.GLQ.VXACwF3h1KQ.VXACMVaPfSxDAXgELDafrVzDA.oUNDafgX0DA.oUNDafHc2DAXgELDaPwa1DAXgELDavP4zDA7+CNDavrWyDAXgELDaPfSxDAXgELzXsAbcfSDfEVvPrAbcfSD.jV4PrA..vSD.jV4PrA..vSDvIe3PrASajSDvIe3PrASajSD.lW1PrAYetSD.lW1PrAYetSDfwnzPrASajSDfwnzPrASajSD.5DxPrAQouSD.5DxPrAQouSDfEVvPrAbcfSDfEVvPi0FDW9KQ.H1ICwFfyLLQ.BPaCwFbquKQ.BPaCwFDW9KQ.H1ICMVafr7ODAXNpLDafCzQDAXNpLjX+3ZRDAXNpLDH3rDQt71KCABNKQDf0eyPhABNKQTZ3BzP+3ZRDA3YFMD3.cDQ.dlQCwFHK+CQ.dlQCwFHK+CQ.liJCMVa.OnZDA.KqLDa.7XbDA.KqLjXKqScDA.KqLDPbcGQsjyLCADW2QD.qFzPhADW2QTGVB0PKqScDA3nXMD.OFGQ.NJVCwFvCpFQ.NJVCwFvCpFQ.vxJCMVafr7ODAHQnMDafCzQDAHQnMjXZOlRDs0.nMDXmwDQkYaaCA1YLQD.1Z2PhA1YLQDr0.3PZOlRDwbRCND3.cDQ.txfCwFHK+CQ.txfCwFHK+CQ.RDZCMVY...";
	
	icons.logo = Content.createPath();
	icons.logo.loadFromData(pathData);
	
	// Rhapsody Logo - Reza
	pathData = "129.t01muzuPn+3pBw1mRLqPlxZ8BwVk+TrPrx9.Cw1P51uPn50yBwFGsrvPa4+4BwV4iVuPa4+4BwFOGwsPVsJ.Cw1wfCvPVsJ.Cw1wfCvPjrYGCwlbrDvPkrYGCw1BC1vPLRTDCw1BC1vPWsJ.CwFsE1wPg3J.CwVIFNxPZxV8BMVY";
	
	const rhapsodyLogo = Content.createPath();
	rhapsodyLogo.loadFromData(pathData);

	// Rhapsody logo with background
	pathData = "166.t01N1g0P4++NBwF9hQ0PDzDSBw1N1g0POnIWBwlWIx0PDzDSBMVaCdGVCUdoBIDaTKuVCkxjLIDaDtnVCUbKNIDaffWVCUMKNIDagfWVCYvnRIDaeOJVCw.8UIDaM6IVCUA8UIDaN6IVC4MKNIDadw0UC4MKNIDaLZCVCsQwJIDa7+TVCsQwJIDaXvGVCkXcGIDaCYoUC0MCOIDa.neUCE8lLIzXkA";
	
	const rhapsodyLogoWithBg = Content.createPath();
	rhapsodyLogoWithBg.loadFromData(pathData);
	
	// Trademark
	pathData = "2581.t0F.fs.Q..fmCwF.fs.Q..fmCwlqns.QcXKnCwVrBt.Q9o1nCwV9st.QnsgoCw1Zpu.QhbLpCwF32v.Q1u1pCwVIVx.QyffqCwF.Ez.QtnIrCwFJD1.QBAxrCwVSS3.QRiYsCw1Dx5.QII.tCwFEf8.QarktCwV3b.AQHGJuCwV.nCAQaSsuCw17.GAQrKOvCwlJmJAQfpuvCwVEZNAQppNwCw1EYRAQNGrwCwliiVAQd6GxCwly3ZAQ7BhxCwFJXeAQdY5xCwl3.jAQJ6PyCwlOxnAQZjkyCwldqsAQ5Q3yCwVyqxAQq.IzCwlZx2AQBtWzCwVf97AQnWjzCw1NOBBQZ6tzCw1viGBQtW2zCwlO6LBQMq8zCwFzTRBQ1zA0CwVmuWBQ.zC0CwlwJcBQTnC0CwlakhBQ1QA0CwVs9mBQ8v7zCwFvUsBQXF1zCwFsoxBQJSszCwls42BQvXhzCw16D8BQ1XUzCwFiJBCQhUFzCwFuIGCQPQ0yCwlrALCQtNhyCwVpwPCQ9PMyCwF2XUCQXa1xCw1i1YCQiwcxCw1BJdCQeWCxCwFnRhCQXQmwCwVoOlCQtiIwCw1c.pCQRSpvCwlejsCQDkIvCwVI6vCQRdmuCwV4CzCQZDDuCwVO91CQFcetCwlso4CQMt4sCwV3E7CQw8RsCwFWR9CQ.RqrCw1xN.DQNwBrCwF35ADQ8gYqCwlUVCDQvpupCwV7fDDQVREpCwlfZEDQdeZoCwF4BFDQAYunCwl+YFDQ3EDnCwF.fFDQ..fmCwF.fFDQ..fmCwF.fFDQ..fmCwlTWFDQjmzlCw1S8EDQDVIlCw1AREDQaRdkCwVkUDDQhiyjCwVHHCDQOPIjCwF2oADQReeiCwV.6+CQWW1hCwV168CQD+MhCwVsr6CQzblgCwF7M4CQ91+fCw16e1CQtSZfCwlHiyCQAxqeCwl.XvCQaYkdCwVD+rCQ4ngcCwl1XoCQPqfbCw16kkCQ5phaCwV6lgCQxwmZCwlcbcCQRIvYCwlMGYCQT56XCwV2mTCQOMKXCw1H+OCQ1IdWCwlwMKCQT2zVCwlhTFCQSbOVCw1MTACQu9sUCwllM7BQBjPUCwFgA2BQ1P2TCwVxvwBQPIhTCwVPbrBQlPQTCwlwDmBQnoDTCwFMqgBQTV7SCw1YPbBQAX3SCwlO0VBQXu3SCwlkZQBQTb8SCwlSALBQDdFTCw1PpFBQNySTCwFTVABQnYkTCwlSF7AQdN6TCwFE61AQPNUUCwFd0wAQ1TyUCw1Q1rAQZcUVCwFT9mAQdh6VCwlVNiAQ9ckWCwlImdAQKISXCw1bIZAQybDYCw180UAQ7P4YCwlXsQAQJcwZCwVWvMAQb3raCwlh+IAQTYqbCwFgaFAQw0rcCwF2DCAQUCwdCwFG7+.QE22eCwFwA8.Q1hffCw1RV5.QvQFgCwFH52.QKBsgCwVos0.Q8sThCwlMwy.QtN8hCwFHEx.Q.dliCw1pov.QLUPjCw1Ceu.Qms5jCwlekt.QdfkkCwFG8s.Q6lPlCwV.ls.QD56lCwF.fs.Q..fmCwF.fs.Q..fmCMVa..XQDA..dNDa..XQDA..dNDaUXWQDUTFgNDaZgUQD4HLjNDaiaRQDI9PmNDaOGNQDcTTpNDaJkHQDsrUsNDaM1AQD4mTvNDac64PDgmPyNDaJ1vPDgMI1NDaymlPDQ783NDa+QaPDAWt6NDai1NPDYAZ9NDadWAPDAf.AODa41xODMXgCODaJWiODQP7EODav5RODcuPHODaQjAOD8cdJODagVuNDAEkLODaZTbNDYOjNODa9fHNDYnaPODaX+yMDI8JRODa6xdMDw6wSODa+9HMDwSPUODaCmxLDI1kVODattaLDIUxWODanYDLDcj0XODagqrKDgYuYODaLnTKD0peZODadS7JD4PFaODaRwiJDYEiaODagEKJD4C1aODaJTxIDII+aODaHgYIDwS9aODabv.ID4iyaODa.FnHDU6daODazkOHDQc.aODavS2GDoNXZODatSeGD4UlYODaioGGD85pXODaBYvFDYGlWODa4kYFDIFXVODavSCFDoCAUODaNlsEDANgSODaufXEDYz3QODaqFDEDkGHPODaTavDDkYONODaxgcDDs8NLODaHcKDDgHGJODaNP5CDoO3GODaz8oCDAphEODahnZCDkuFCODazRLCDQ4j.ODa799BD4f88NDaEuxBDYAQ6NDaIkmBDQ1e3NDa8hcBDwap0NDaFpTBDEOwxNDa.7LBDwszuNDa5YFBD4U0rNDa1DABDQlyoNDaq87ADo8ulNDaDE5ADg6piNDaca3ADY+jfNDa..3ADA..dNDa..3ADA..dNDa..3ADA..dNDaqm3ADoq4ZNDald5ADA2yWNDacj8ADwAuTNDaw3ABDUqqQNDa2ZGBDASpNNDazINBDwWqKNDajDVBDIXuHNDa2IeBDEx1ENDaOXoBDQCBCNDaCtzBDgnQ.NDafIACDI7K6MDalnNCD4990MDaJIcCDYN8vMDa5nrCDMdGrMDaUE8CD4edmMDazaNDD4BCiMDakofDDkz0dMDasqyDDAf2ZMDaIeGED8sHWMDav.bEDgDpSMDaNMwEDQGbPMDaJAGFDQWeMMDaGYcFDoRzJMDacQzFDwTaHMDailKGDI1TFMDaqTiGDQLgDMDaAX6GDoo.CMDaurSHDscyAMDa7NrHDwz4.MDas5DIDE3S.MDaErcIDwsA.MDaGe1IDsXC.MDazOOJDg3X.MDaP5mJD4IBAMDacZ.KDMF+AMDagrXKDsiOCMDajrvKDgUyDMDatVHLDkKpFMDaPmeLDAyyHMDaYZ1LD00OKMDagrLMD858MMDaDZhMDkl8PMDahe2MDEZNTMDal4KND8yuWMDa8jeNDQPgaMDaddxNDUHheMDaHiDODEywiMDaBvUODAkOnMDaZBlODcv5rMDarW0ODgkxwMDaYsCPDUR11MDaOAQPDICE7MDaFQcPDMAu.NDa.anPDYLfCNDaLcxPD4lUFNDaAV6PDoyNINDaFDCQDAUKLNDaLlIQD4rJONDaN6NQDobLRNDaXBSQDMEPUNDa95UQDUGUXNDajjWQDgCaaNDa..XQDA..dNDa..XQDA..dNzXsA.zbPD7G32Pr8Q2nPD7G32PhAWeuPD7G32Pwv2LDYliFNTL7MCQbRgjCIVL7MCQlYtlCcn4vPjjcD5PmDaKDQLbiNDa..AMDA..8NDaovhKDA..8NDaWOHJDcSJkNDaP0eHDcSJkNDaP0eHDA..8NDa..MGDA..8NDa..MGDA+A9MzXsIE+gPzg1c3PrIE+gPDF7y4Pr4N+mPDF7y4Phg+0qPDF7y4PXUgKDEXYYNDVU3BQaGmjCIFVU3BQ240hC0gwqPzg1c3PjBBJDcncGNDaRweHDcncGNzXkA";
	
	icons.trademark = Content.createPath();
	icons.trademark.loadFromData(pathData);
}  